services:
  # main-app:
  #   build: .
  #   restart: always
  #   ports:
  #     - "${PORT}:${PORT}"
  #   environment:
  #     - PORT=${PORT}
  #     - ENV=${ENV}
  #     - LOG_LEVEL=${LOG_LEVEL}
  #     - LOG_FORMAT=${LOG_FORMAT}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
  #     - REDIS_URL=redis://redis:6379/0
  #     - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
  #     - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
  #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
  #     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
  #     - REDIRECT_URL=${REDIRECT_URL}
  #     - ADMIN_EMAIL=${ADMIN_EMAIL}
  #     - QUEUE_URL=http://aws:4566/000000000000/order-expiration-queue
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  #     - AWS_ENDPOINT_URL_SQS=${AWS_ENDPOINT_URL_SQS}
  #   depends_on:
  #     - postgres
  #     - redis
  #     - aws
  #   volumes:
  #     - ./localhost+2.pem:/app/localhost+2.pem
  #     - ./localhost+2-key.pem:/app/localhost+2-key.pem
# 
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
    - ./redis-data:/data  # Persist Redis datad

  aws:
    image: localstack/localstack
    restart: always
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # Collector HTTP
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

